---
title: "hw01_gapminder"
author: "Xinzhe Dong"
date: "September 16, 2017"
output: 
  github_document
---

Get an overview of the gapminder dataframe
```{r}
library(gapminder)
str(gapminder)
```

Print gapminder to screen
```{r}
library(tidyverse)
gapminder
```

A statistical overview obtained with summary()
```{r}
summary(gapminder)
```

Some basic plots
```{r}
plot(lifeExp ~ year, gapminder)
plot(lifeExp ~ gdpPercap, gapminder)
plot(lifeExp ~ log(gdpPercap), gapminder)
barplot(table(gapminder$continent))

```

Exploit the fact that ggplot2 was installed and loaded via the tidyverse
```{r}
p <- ggplot(filter(gapminder, continent != "Oceania"),
            aes(x = gdpPercap, y = lifeExp)) # just initializes
p <- p + scale_x_log10() # log the x axis the right way
p + geom_point() # scatterplot
p + geom_point(aes(color = continent)) # map continent to color
p + geom_point(alpha = (1/3), size = 3) + geom_smooth(lwd = 3, se = FALSE)
p + geom_point(alpha = (1/3), size = 3) + facet_wrap(~ continent) +
  geom_smooth(lwd = 1.5, se = FALSE)
```

